name: macOS build for vnu

on:
  pull_request:

jobs:
  darwin:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java JDK
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 16
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Update submodules
        run: python ./checker.py update
      - name: Install dependencies
        run: python ./checker.py dldeps
      - name: Build
        uses: ./.github/actions/build
